service: my-express-application

provider:
  name: aws
  runtime: nodejs18.x # Nodejs version used by AWS Lambda functions
  stage: dev # Specify the stage of your application
  region: sa-east-1 # Specify the region of your application
  environment:
    NODE_ENV: production # Set the environment to production

functions:
  app: # The name of the AWS Lambda function
    handler: src/main.handler
    events:
      - http:
          path: "{proxy+}" # This captures all paths
          method: any # This allows any HTTP method
          cors: true

plugins:
  - serverless-offline # For emulating AWS Lambda and API Gateway locally
  - serverless-dotenv-plugin # For loading env variables from a .env file
  - serverless-webpack
  # - serverless-bundle # For bundling the project

custom:
  serverless-offline:
    httpPort: 3000 # The port serverless-offline will run on
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore


package:
  individually: true # This will package each function individually
  exclude:
    - node_modules/**
    - .git/**
  include:
    - ./src/** # Make sure to include your source files
